### ISSUE TITLE
Does DevOps Insights support JUnit Unit tests?

### ISSUE THREAD

**Issue by matyasforian** [IBM-Bluemix-Docs/DevOpsInsights#10]
In this page: https://github.com/IBM-Bluemix-Docs/DevOpsInsights/blob/master/risk_cd.md I dont see JUnit as a supported test type, but here: https://www.npmjs.com/package/grunt-idra3 (under supported tag formats) it tells me that JUnit is supported. 

So can I Use JUnit test results as an input to DevOps insights?

**Comment by KentHall2018** [comment]
https://github.com/IBM-Bluemix-Docs/DevOpsInsights/blob/master/risk_cd.md page no longer exists. JUnit support is mentioned through the docs now. https://cloud.ibm.com/docs/services/DevOpsInsights?topic=DevOpsInsights-adding-data-sets
